server:
  port: 8090
  context-path: /clientB

security:
  oauth2:
    client:
      client-id: clientB
      client-secret: secretB
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
